name: nf-core linting
# This workflow is triggered on pushes and PRs to the repository.
# It runs the nf-core linting tools to ensure that the pipeline meets the nf-core guidelines.

on:
  push:
    branches:
      - dev
      - main
      - master
  pull_request:
  release:
    types: [published]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files || echo "Pre-commit failed, but continuing"

  EditorConfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: editorconfig-checker/action-editorconfig-checker@main

      - run: editorconfig-checker -exclude README.md $(find .* -type f | grep -v '.git\|.github\|.pytest_cache')

  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Prettier
        run: |
          npm install -g prettier
          prettier --check ${GITHUB_WORKSPACE}

  nf-core:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install nf-core tools
        run: |
          python -m pip install --upgrade pip
          pip install nf-core

      - name: Run nf-core lint
        run: nf-core lint ${GITHUB_WORKSPACE} --release
